/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class deathNote */

#ifndef _Included_deathNote
#define _Included_deathNote
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     deathNote
 * Method:    addition
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_deathNote_addition
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     deathNote
 * Method:    subtraction
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_deathNote_subtraction
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     deathNote
 * Method:    multiplication
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_deathNote_multiplication
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     deathNote
 * Method:    division
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_deathNote_division
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     deathNote
 * Method:    sine
 * Signature: (I)F
 */
JNIEXPORT jfloat JNICALL Java_deathNote_sine
  (JNIEnv *, jobject, jint);

/*
 * Class:     deathNote
 * Method:    cosine
 * Signature: (I)F
 */
JNIEXPORT jfloat JNICALL Java_deathNote_cosine
  (JNIEnv *, jobject, jint);

/*
 * Class:     deathNote
 * Method:    tangent
 * Signature: (I)F
 */
JNIEXPORT jfloat JNICALL Java_deathNote_tangent
  (JNIEnv *, jobject, jint);

/*
 * Class:     deathNote
 * Method:    sqrt
 * Signature: (I)F
 */
JNIEXPORT jfloat JNICALL Java_deathNote_sqrt
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
